### ISSUE TITLE
我使用sts assumeRole功能时出现这个问题,是功能没实现么

### ISSUE THREAD

**Issue by zhhao226** [denverdino/aliyungo#241] opened 2018-01-14 03:09 UTC
我log打出来的url是Invoke GET https://location.aliyuncs.com，sts官方文档url是https://sts.aliyuncs.com，
使用方式：
client := sts.NewClient(accessKeyId,secretAccessKey)
	client.SetEndpoint(endPoint)
	//policy := fmt.Sprintf(policy,"test",uid)
	fmt.Println(policy)
	assumeRoleRequest := sts.AssumeRoleRequest{
		RoleArn:roleArn,
		RoleSessionName:"session111",
		DurationSeconds:3600,
		Policy:policy,
	}
assumeRoleResponse,err := client.AssumeRole(assumeRoleRequest)
一直报错这个
2018/01/14 10:58:46 {
    "Message": "Id is mandatory for this action.",
    "RequestId": "3E02B29D-57A4-418A-881F-9657C9AE8106",
    "HostId": "location.aliyuncs.com",
    "Code": "MissingId"
}

**Comment by denverdino** [comment] 2018-01-14 06:49
Dupe of #236

**Closed by denverdino** 2018-01-14 06:49 UTC

**Comment by zhhao226** [comment] 2018-01-15 07:40
我绕过了sts client定义，自己初始化了common client实现了功能：
	client := &common.Client{}
	client.Init(endPoint,apiVersion,accessKeyId,secretAccessKey)
	assumeRoleResponse := sts.AssumeRoleResponse{}
	assumeRoleRequest := sts.AssumeRoleRequest{
		RoleArn:roleArn,
		RoleSessionName:"sessionuser",
		DurationSeconds:3600,
		Policy:policy,
	}
	err := client.Invoke("AssumeRole", assumeRoleRequest, &assumeRoleResponse)
